[build]
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"
rustflags = [
    "-Clink-args=-nostartfiles",
    "-Clink-args=-Wl,-n,-N,--no-dynamic-linker,--build-id=none",
    "-Crelocation-model=static"
]
